### ISSUE TITLE
AutoMarkMessageRead 个别API调用情况下报错

### ISSUE THREAD

**Issue by traceless0929** [Hoshikawa-Kaguya/Sora#36]
**使用环境**
 -  框架版本号:`rc17`
 -  运行环境:`CentOS 7.6.1810   go-cqhttp v1.0.0-beta6`

**bug描述**
SetFriendAddRequest调用后功能正常但是触发go-cqhttp处理ws命令失败导致WS重连

**如何复现**
1. OnFriendRequest捕获OnFriendRequest，并输出RequsetFlag
2. 创建一个同意好友的私聊指令并调用await args.SoraApi.SetFriendAddRequest(flag, true);
3. 向机器人发送flag触发指令
4. 触发同意后，好友添加成功，但是WS断开连接，go-cqhttp报错如下
```C#
[2021-08-23 19:12:40] [INFO]: 处置WS命令时发生无法恢复的异常：interface conversion: interface {} is int32, not int64
goroutine 479997 [running]:
runtime/debug.Stack(0xc0008417a0, 0xd78000, 0xc001ec8510)
	runtime/debug/stack.go:24 +0x9f
github.com/Mrs4s/go-cqhttp/server.(*webSocketConn).handleRequest.func1(0xc000a00690)
	github.com/Mrs4s/go-cqhttp/server/websocket.go:372 +0x5b
panic(0xd78000, 0xc001ec8510)
	runtime/panic.go:965 +0x1b9
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQMarkMessageAsRead(0xc00029a0c0, 0xc071d2e6b3, 0xa)
	github.com/Mrs4s/go-cqhttp/coolq/api.go:1434 +0xb0f
github.com/Mrs4s/go-cqhttp/server.markMSGAsRead(0xc00029a0c0, 0xfb3140, 0xc0007fb240, 0x10)
	github.com/Mrs4s/go-cqhttp/server/api.go:354 +0xcc
github.com/Mrs4s/go-cqhttp/server.(*apiCaller).callAPI(0xc0003f5640, 0xc0010ec40b, 0x10, 0xfb3140, 0xc0007fb240, 0xc0010ec454)
	github.com/Mrs4s/go-cqhttp/server/api.go:430 +0x409
github.com/Mrs4s/go-cqhttp/server.(*webSocketConn).handleRequest(0xc000a00690, 0xc00029a0c0, 0xc0010ec400, 0x6e, 0x3d6)
	github.com/Mrs4s/go-cqhttp/server/websocket.go:379 +0x5a5
github.com/Mrs4s/go-cqhttp/server.(*webSocketServer).listenAPI.func2(0xc000a00690, 0xc0007aa060, 0xc000ceba10)
	github.com/Mrs4s/go-cqhttp/server/websocket.go:361 +0x9d
created by github.com/Mrs4s/go-cqhttp/server.(*webSocketServer).listenAPI
	github.com/Mrs4s/go-cqhttp/server/websocket.go:359 +0x10e
 
[2021-08-23 19:12:40] [INFO]: 接受 WebSocket 连接: 127.0.0.1:60306 (/) 

```
怀疑是启用了AutoMarkMessageRead导致的个别特殊API调用报错

**错误截图或日志**
需要具体核实情况可以QQ 415206409

**Comment by Yukari316** [comment]
这个和gocq的开发者已经确认过是gocq的bug
应该会在下一个gocq版本修复
在修复之前请暂时将 `AutoMarkMessageRead` 置为 `false` 以停用自动标记的功能

**Comment by traceless0929** [comment]
> 这个和gocq的开发者已经确认过是gocq的bug
> 应该会在下一个gocq版本修复
> 在修复之前请暂时将 `AutoMarkMessageRead` 置为 `false` 以停用自动标记的功能

停用自动标记的话，不标记会有什么副作用么？

**Comment by Yukari316** [comment]
可能会导致gocq在私聊重复收到相同的消息
不过这个也是之前就有的问题了，暂时只能自己在应用层过滤重复的私聊信息

**Comment by traceless0929** [comment]
> 这个和gocq的开发者已经确认过是gocq的bug
> 应该会在下一个gocq版本修复
> 在修复之前请暂时将 `AutoMarkMessageRead` 置为 `false` 以停用自动标记的功能

GOCQ那边修复了嘛

**Comment by Yukari316** [comment]
新版本已经修复了
