### ISSUE TITLE
长期运行偶尔崩溃

### ISSUE THREAD

**Issue by cc004** [Hoshikawa-Kaguya/Sora#41]
**使用环境**
 -  框架版本号:`0.9.9.0`
 -  运行环境:`cqhttp 1.0.0 beta6`

**bug描述**
崩溃

**如何复现**
不知道，偶尔遇到

**错误截图或日志**
```
[2021/9/5 21:01:02][FATAL][System]检测到未处理的异常进程将停止运行，错误信息:
==============ERROR==============
Error:System.InvalidOperationException

Message:Collection was modified; enumeration operation may not execute.

Stack Trace:
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at Sora.Net.ConnectionManager.HeartBeatCheck(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
=================================
```
忘记圈起来果然还是很丢人，虽然close了还是改一下

**Comment by Yukari316** [comment]
新版本中修复掉了，可以尝试使用新版本`>rc19`
这个算是个历史遗留问题了（
不太建议继续用旧版本

**Comment by Yukari316** [comment]
不过我也不是特别清楚你那边是否是这个问题，等你那边测试没事之后再关闭这个issue了

**Comment by cc004** [comment]
好像目前就没啥问题了。。。先close吧，再出问题再说
